#!/bin/bash

clear
echo -e "==============================================="
echo -e "*      Script Auto Install SSH / OVPN         *"
echo -e "==============================================="
echo -e "*                                             *"
echo -e "==============================================="
echo -e "*     Source Detail = Internet / Google       *"
echo -e "==============================================="
echo -e "*                                             *"
echo -e "==============================================="
echo -e "*            Ucapan Terima Kasih              ="
echo -e "==============================================="
echo -e "* - Terima Kasih Banyak Kepada Google         *"
echo -e "* - Terima Kasih Kepada www.malasngoding.com  *"                                         
echo -e "* - Terima Kasih Kepada Source Yang Di Github *"    
echo -e "* - Terima Kasih Kepada My Family             *"    
echo -e "* - Terima Kasih Kepada Kepada Kalian         *"    
echo -e "==============================================="
echo -e "*            Created By WILDYVPN              *"
echo -e "*  Semoga Script Ini Dapat Beguna BagI Semua  *"
echo -e "==============================================="
echo -e "*                                             *"
echo -e "==============================================="
echo -e "*                   Contact                   *"
echo -e "==============================================="
echo -e "* Telegram : https://t.me/wildyssh/           *"
echo -e "* Whatsapp : https://wa.me/6289635284000/     *"
echo -e "==============================================="

