#!/bin/bash
#script created by wildyvpn
neofetch
echo -e "================== SSH / OVPN ========================"
echo -e "* utama          : Menampilkan Menu Menu yang ada    *"
echo -e "* tambah         : Membuat akun SSH & OVPN Baru      *"
echo -e "* percobaan      : Membuat akun SSH & OVPN Percobaan *"
echo -e "* hapus          : Menghapus akun Yang Bandel        *"
echo -e "* cek            : Cek Siapa Saja Yang Login         *"
echo -e "* anggota        : Cek Semua Anggota Di SSH / OVPN   *"
echo -e "* delexp         : Menghapus Akun Yang Expired       *"
echo -e "================== SSH / OVPN ========================"
echo -e "*     WILDY VPN AUTO INSTALL SSH / OVPN SCRIPT       *"
echo -e "================== Menu System ======================="
echo -e "» restart        : Merestart Semua Menu VPN          *"
echo -e "» ressh          : Merestart SSH                     *"
echo -e "» redrop         : Merestart Dropbear                *"
echo -e "» resquid        : Merestart Squid Proxy             *"
echo -e "» reovpn         : Merestart OVPN Service            *"
echo -e "» restun         : Merestart Stunnel                 *"
echo -e "» remin          : Merestart Webmin                  *"
echo -e "» reboot         : Merestart Server VPS              *" 
echo -e "» ujicoba        : Mencoba Kecepatan Jaringan        *"
echo -e "» info           : Menampilkan Informasi System      *"
echo -e "» about          : Menampilkan Informasi Script      *"
echo -e "» exit           : Logout Dari Server                *"
echo -e "==================== Tambahan ========================"
echo -e "* installvpn     : Meningstall Package L2TP          *"
echo -e "* addvpn         : Membuat Akun L2TP Baru            *"
echo -e "* delvpn         : Menghapus Akun L2TP               *"
echo -e "================== Menu System ======================="
echo -e "*                                                    *"
echo -e "*           Script Created By WILDYVPN               *"
echo -e "*               WA = 0896-3528-4000                  *"
echo -e "*                                                    *"
echo -e "=================== Thanks You ======================="